
import React, { useState, useEffect } from 'react';
import { Code, Play, Save, Layers, Smartphone, Download, Lock, Shield, Upload } from 'lucide-react';
import { useKernel } from '../context/KernelContext';
import { AppDefinition, AppManifest } from '../types';

const XlineStudio: React.FC = () => {
  const { installApp, generateDeveloperCertificate, userProfile, createFile, importDeveloperCertificate } = useKernel();
  const [activeTab, setActiveTab] = useState<'wizard' | 'code'>('wizard');
  const [showCertWizard, setShowCertWizard] = useState(false);
  
  // Wizard State
  const [appName, setAppName] = useState('');
  const [appId, setAppId] = useState('com.xlinelabs.');
  const [appUrl, setAppUrl] = useState('');
  const [iconUrl, setIconUrl] = useState('https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=128&h=128&fit=crop');
  
  // Cert State
  const [certPassword, setCertPassword] = useState('');
  const [importCertData, setImportCertData] = useState('');

  // Check cert on load
  useEffect(() => {
      if (!userProfile.developerCertificate) {
          setShowCertWizard(true);
      }
  }, [userProfile.developerCertificate]);
  
  const generatePackage = async () => {
    if (!appName || !appId) {
        alert("Please fill all fields.");
        return null;
    }

    if (!userProfile.developerCertificate) {
        setShowCertWizard(true);
        return null;
    }

    const manifest: AppManifest = {
        packageId: appId,
        name: appName,
        version: '1.0.0',
        iconUrl: iconUrl,
        minOsVersion: '1.0',
        permissions: ['internet'],
        developerSignature: userProfile.developerCertificate
    };

    const packageData = {
        id: `app_${Date.now()}`,
        manifest,
        type: 'USER',
        config: { url: appUrl },
        sourceCode: activeTab === 'code' ? "// Custom Code" : `/* Generated by Wizard */\nwebview.load('${appUrl}')`
    };

    return packageData;
  };

  const handleInstall = async () => {
    const pkg = await generatePackage();
    if (pkg) {
        const newApp: AppDefinition = {
            id: pkg.id,
            manifest: pkg.manifest,
            type: 'USER',
            component: () => (
                <iframe src={pkg.config.url} className="w-full h-full border-0 bg-white" title={pkg.manifest.name} />
            )
        };
        installApp(newApp);
        // Also save to internal FS
        createFile('projects', `${pkg.manifest.name.replace(/\s/g,'_')}.xos`, JSON.stringify(pkg, null, 2));
        alert(`App installed locally and project saved to /home/user/projects/`);
    }
  };

  const handleExport = async () => {
      const pkg = await generatePackage();
      if (pkg) {
          const blob = new Blob([JSON.stringify(pkg, null, 2)], { type: 'application/x-xos' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${pkg.manifest.packageId}.xos`;
          a.click();
          URL.revokeObjectURL(url);
      }
  };

  const handleGenerateCert = async () => {
      if (!certPassword) return alert("Password required");
      await generateDeveloperCertificate(certPassword);
      // Auto download cert backup
      const blob = new Blob([userProfile.developerCertificate || ''], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${userProfile.username}.cert`;
      a.click();
      URL.revokeObjectURL(url);
      setShowCertWizard(false);
  };

  const handleImportCert = async (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) {
          const reader = new FileReader();
          reader.onload = async (evt) => {
              const content = evt.target?.result as string;
              setImportCertData(content);
          };
          reader.readAsText(file);
      }
  };

  const confirmImport = async () => {
      if (!importCertData || !certPassword) return alert("File and password required");
      const success = await importDeveloperCertificate(importCertData, certPassword);
      if (success) {
          setShowCertWizard(false);
          alert("Certificate Imported Successfully");
      } else {
          alert("Import failed. Invalid password or corrupt file.");
      }
  };

  return (
    <div className="flex flex-col h-full bg-[#1e1e1e] text-gray-300 font-sans relative">
      {/* Cert Wizard Modal */}
      {showCertWizard && (
          <div className="absolute inset-0 bg-black/80 z-50 flex items-center justify-center p-8">
              <div className="bg-[#252526] p-6 rounded-xl border border-white/10 max-w-lg w-full shadow-2xl">
                  <div className="flex items-center gap-3 mb-4 text-blue-400">
                      <Shield size={24} />
                      <h2 className="text-xl font-bold">Developer Certificate Missing</h2>
                  </div>
                  <p className="text-sm text-gray-400 mb-6">
                      To build and sign apps for XlineOS, you need a Developer Certificate. You can generate a new one or import an existing `.cert` file.
                  </p>

                  <div className="space-y-4">
                      <input 
                        type="password" 
                        placeholder="Enter Signing Password" 
                        className="w-full bg-[#3c3c3c] p-2 rounded border border-white/5 outline-none"
                        value={certPassword}
                        onChange={e => setCertPassword(e.target.value)}
                      />
                      
                      <div className="grid grid-cols-2 gap-4">
                          <button onClick={handleGenerateCert} className="bg-blue-600 hover:bg-blue-500 text-white p-2 rounded text-sm font-bold">
                              Generate & Download New
                          </button>
                          
                          <div className="relative">
                              <input type="file" className="absolute inset-0 opacity-0 cursor-pointer" onChange={handleImportCert} />
                              <button className="w-full bg-gray-700 hover:bg-gray-600 text-white p-2 rounded text-sm font-bold flex items-center justify-center gap-2">
                                  <Upload size={14} /> {importCertData ? 'File Selected' : 'Import .cert'}
                              </button>
                          </div>
                      </div>
                      
                      {importCertData && (
                          <button onClick={confirmImport} className="w-full bg-green-600 hover:bg-green-500 text-white p-2 rounded text-sm font-bold">
                              Confirm Import with Password
                          </button>
                      )}
                  </div>
              </div>
          </div>
      )}

      {/* Toolbar */}
      <div className="h-12 bg-[#252526] flex items-center px-4 border-b border-black/50 justify-between">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 font-bold text-white">
            <Layers className="text-blue-500" size={20} />
            Xline Studio <span className="text-xs text-gray-500 font-normal">v2.2</span>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
           <button onClick={handleInstall} className="flex items-center gap-2 bg-green-600 hover:bg-green-500 text-white px-3 py-1 rounded text-xs font-bold">
             <Play size={14} /> Build & Install
           </button>
           <button onClick={handleExport} className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-3 py-1 rounded text-xs font-bold">
             <Download size={14} /> Export .xos
           </button>
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Sidebar */}
        <div className="w-64 bg-[#252526] border-r border-black/50 flex flex-col">
            <div className="p-4">
                <div className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">Properties</div>
                <div className="space-y-4">
                    <div>
                        <label className="text-xs block mb-1">App Name</label>
                        <input className="w-full bg-[#3c3c3c] rounded p-1 text-sm outline-none" value={appName} onChange={e => setAppName(e.target.value)} placeholder="MyApp" />
                    </div>
                    <div>
                        <label className="text-xs block mb-1">Package ID</label>
                        <input className="w-full bg-[#3c3c3c] rounded p-1 text-sm outline-none" value={appId} onChange={e => setAppId(e.target.value)} />
                    </div>
                    <div>
                        <label className="text-xs block mb-1">Icon URL</label>
                        <input className="w-full bg-[#3c3c3c] rounded p-1 text-sm outline-none" value={iconUrl} onChange={e => setIconUrl(e.target.value)} />
                    </div>
                    <div>
                        <label className="text-xs block mb-1">Webview URL</label>
                        <input className="w-full bg-[#3c3c3c] rounded p-1 text-sm outline-none" value={appUrl} onChange={e => setAppUrl(e.target.value)} placeholder="https://..." />
                    </div>
                </div>
            </div>
            
            <div className="mt-auto p-4 border-t border-white/10 bg-black/20">
                <div className="text-xs font-bold uppercase tracking-wider text-green-400 mb-2 flex items-center gap-1">
                    <Shield size={12} /> Certificate Active
                </div>
                <div className="text-xs text-gray-500 break-all">
                    {userProfile.developerCertificate?.substring(0, 30)}...
                </div>
            </div>
        </div>

        {/* Preview */}
        <div className="flex-1 bg-[#1e1e1e] flex flex-col items-center justify-center p-10">
            <div className="w-64 h-64 border-2 border-dashed border-gray-600 rounded-2xl flex flex-col items-center justify-center gap-4">
                <img src={iconUrl} className="w-24 h-24 rounded-2xl shadow-lg" alt="Icon Preview" onError={(e) => (e.currentTarget.src = 'https://via.placeholder.com/128')} />
                <div className="text-center">
                    <div className="font-bold text-white">{appName || 'Untitled App'}</div>
                    <div className="text-xs text-gray-500">{appId}</div>
                </div>
            </div>
            <p className="mt-8 text-gray-500 text-sm max-w-md text-center">
                Project will be saved to <code>/home/user/projects/</code> on build.
            </p>
        </div>
      </div>
    </div>
  );
};

export default XlineStudio;
